### PR TITLE
Restore rparWith behavior

### LINKED ISSUE #35: Regression: The behaviour of `rparWith r0` has changed
For years the documented (and actual) behaviour of `rparWith r0`, was to create a spark that does no evaluation. However since commit 9ea4c073e9fafc81d2a771831a2f913153c36214 the spark will evaluate to weak head normal form.

I have restored the documented behaviour in pull request #34.

### PR DESCRIPTION
**Pull request by treeowl**
* Lift the result to avoid always reducing to WHNF.
* Rewrite the documentation of `rparWith`.

Fixes #35

### CODE REVIEW

**Comment by treeowl** [comment]
Now that I understand `rparWith` better, I think I also understand why some of those `RULES` were important. But I still think we can do better by using "low-level" rules and letting high-level constructs inline enough. In addition to the evaluation rules

```haskell
runEval (r0 a) = a
runEval (rpar a) = a
runEval (rseq a) = a
```

we need

```haskell
rparWith r0 = r0
rparWith rpar = rpar
rparWith rseq = rpar
```

File: Control/Parallel/Strategies.hs [hunk 1]
```diff
@@ -432,19 +432,33 @@ rpar  x = case (par# x) of { _ -> Done x }
...
---  * does not exit the `Eval` monad
---
---  * does not have a built-in `rseq`, so for example `rparWith r0`
---    behaves as you might expect (it is a strategy that creates a
---    spark that does no evaluation).
+-- @
+-- rparWith strat x
+-- @
 --
+-- will spark a thread to perform @strat x@ in parallel. Note
```
Comment (simonmar) [inline Control/Parallel/Strategies.hs]: let's not use the terminology "thread" here to avoid confusion. How about "will spark @strat x@".

File: Control/Parallel/Strategies.hs [hunk 2]
```diff
@@ -432,19 +432,33 @@ rpar  x = case (par# x) of { _ -> Done x }
...
+-- that @rparWith strat@ is /not/ the same as @rpar `dot` strat@.
+-- Specifically, @rpar `dot` strat@ always produces a value in
+-- WHNF, while @rparWith strat@ need not.
 --
+-- > rparWith r0 = r0
+-- > rparWith rpar = rpar
```
Comment (simonmar) [inline Control/Parallel/Strategies.hs]: The LHS creates two sparks, I'm not sure I'd call them equal. It depends what equality you're using, but as I argued elsewhere the only sensible notions of equality here are ones that care about sparks.

**Comment by treeowl** [comment]
I don't think it pays too much to distinguish too much between sparks that
are (almost) guaranteed to fizzle and sparks that don't spark, especially
since I think it reasonable to use rewrite rules to turn the former into
the latter.

File: Control/Parallel/Strategies.hs [hunk 3]
```diff
@@ -432,19 +432,33 @@ rpar  x = case (par# x) of { _ -> Done x }
...
+rparWith s a = do
+  l <- rpar r
+  return (case l of Lift x -> x)
+
+  where
+    r = runEval (Lift <$> s a)
+
+data Lift a = Lift a
 #else
 rparWith s a = do l <- rpar (s a); return (case l of Done x -> x)
```
Comment (Borgvall) [inline Control/Parallel/Strategies.hs]: AFAIK, we can also use the GHC >= 7.2 version here, saving some code dupling.

Comment (treeowl) [reply Control/Parallel/Strategies.hs]: Good point.

File: Control/Parallel/Strategies.hs (hunk 2 above)
Comment (Borgvall) [reply Control/Parallel/Strategies.hs]: `rparWith rpar` is actually a quite weird thing: it creates a spark, who creates a spark, who evaluates to WHNF.

However one can probably replace that law with `rparWith rseq = rpar`.

Comment (treeowl) [reply Control/Parallel/Strategies.hs]: How does one replace the other? What we probably actually want is some sort of equivalence relation that equates "essentially equivalent" things. `rpar x >>= rseq` is effectively the same as `rseq x`, but I don't know how to express that.

File: Control/Parallel/Strategies.hs [hunk 4]
```diff
@@ -432,19 +432,33 @@ rpar  x = case (par# x) of { _ -> Done x }
...
+-- > rparWith rpar = rpar
+-- > rparWith rseq = rpar
 rparWith :: Strategy a -> Strategy a
 #if __GLASGOW_HASKELL__ >= 702
-rparWith s = rpar `dot` s
+-- The intermediate `Lift` box is necessary, in order to avoid a built-in
+-- `rseq` in `rparWith`. In particular, we want rparWith r0 = r0, not
+-- rparWith r0 = rpar.
+rparWith s a = do
+  l <- rpar r
```
Comment (Borgvall) [inline Control/Parallel/Strategies.hs]: This creates (nearly) always a fizzled spark, because `l` is immediately pattern matched. A lazy pattern match is needed.

Comment (treeowl) [reply Control/Parallel/Strategies.hs]: The pattern match is lazy (it's in the argument to `return`). Try your test!

File: Control/Parallel/Strategies.hs (hunk 2 above)
Comment (treeowl) [reply Control/Parallel/Strategies.hs]: @simonmar, my intuition suggests that we're never going to find all the relations (`Eval` is a very large structure), but that we should document some of the more useful ones. It's easy to *think* you're getting more parallelism than you are when composing things. Speaking of relations,

```haskell
runEval (m >>= rpar) = runEval m

rpar x >>= \x' -> rpar y >>= f  =  rpar y >>= \y' -> rpar x >>= f
-- when x' is not free in y and y' is not free in x.
```

File: Control/Parallel/Strategies.hs (hunk 4 above)
Comment (treeowl) [reply Control/Parallel/Strategies.hs]: Moreover, if you inline everything manually (including the `runRW#`) you'll end up with the same thing as the old implementation. We just shouldn't do that because inlining the `realWorld#` is like asking the optimizer to completely mangle our intentions.

Comment (treeowl) [reply Control/Parallel/Strategies.hs]: (FYI, search the `bytestring` source code for `accursedUnutterablePerformIO` if you want a more detailed explanation.)

Comment (Borgvall) [reply Control/Parallel/Strategies.hs]: Sorry I was wrong with my comment.
